//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guide
    {
        public int g_Id { get; set; }
        public string g_name { get; set; }
        public string g_contact { get; set; }
        public string g_availability { get; set; }
        public string g_city { get; set; }
    }
}
