//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int h_id { get; set; }
        public string h_name { get; set; }
        public string h_address { get; set; }
        public string h_descrip { get; set; }
        public string h_url { get; set; }
    }
}
