//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        public int s_id { get; set; }
        public string s_name { get; set; }
        public Nullable<double> s_lat { get; set; }
        public Nullable<double> s_long { get; set; }
        public string s_category { get; set; }
    }
}
